### ISSUE TITLE
Possível Freela

### ISSUE THREAD

**Issue by alansystem** [bbarreto/sinesp-api#2]
Boa tarde, vi que você sem tem uma aplicação em Node que faz consulta no Sinesp para retorno de dados do veículo através da placa, sou programador PHP e de Node não manjo, gostaria de saber se existe alguma forma de efetuarmos uma integração, lembrando que como tenho um cliente com interesse, estou disposto a pagá-lo pelo serviço, mas primeiro gostaria de saber a possibilidade e como poderíamos fazer.

Obrigado.

**Comment by diego-vieira** [comment]
@alansystem o programa simplesmente está fazendo uma requisição HTTP enviando alguns headers como se fosse o app. Usando Guzzle você consegue fazer o mesmo.
