### ISSUE TITLE
Atualizar Aplicativo

### ISSUE THREAD

**Issue by avedisb** [bbarreto/sinesp-api#3]
Boa tarde Bruno.

Estou usando o plugin, porem o retorno sempre é : 
 codigoRetorno":"7","mensagemRetorno":"Versão desatualizada. Favor atualizar aplicativo.

Pode me ajudar?

**Comment by bbarreto** [comment]
Pelo que parece, o sinesp alterou o app e a chave da conexão com a API.

Vou tentar arrumar um tempo para quebrar a nova chave e então atualizo o repositório.

**Comment by avedisb** [comment]
Obrigado pelo retorno.
