### ISSUE TITLE
Retorno Erro

### ISSUE THREAD

**Issue by Kkshi28** [bbarreto/sinesp-api#4]
Neste exemplo do GitHub esta retornando
{"codigoRetorno":"7","mensagemRetorno":"Versão desatualizada. Favor atualizar aplicativo."}
No modulo que esta em https://www.npmjs.com/~bbarreto esta retornando
Object {error: Error: unable to verify the first certificate}
@bbarreto

**Comment by bbarreto** [comment]
O erro do certificado acabei de corrigir na versão 1.0.3. O erro de "versão desatualizada" normalmente ocorre quando o SINESP muda a versão do aplicativo deles ou altera a chave de acesso. Se puder colaborar para corrigir o problema, fique à vontade.

**Comment by Kkshi28** [comment]
Honestamente não manjo de node encontrei tua ferramentas e simplesmente utilizo ela para consultar as placas, se me dá um norte do que fazer posso colaborar sem problema mas a verdade não tenho ideia estou passando teu comentário para uma amigo que trabalha com node para ver si ajuda. 
Mas se eles alteraram a chave de acesso tem como nós solucionar isso? no caso de que tenham mudada a versão do app deles que teria que ser feito?

**Comment by brodrigues1990** [comment]
Gostaria de saber também como ajudar, pois essa ferramenta será de grande ajuda na minha aplicação!

**Comment by bbarreto** [comment]
É necessário decompilar ou monitorar o tráfego do aplicativo oficial do SINESP no Android ou iPhone para poder descobrir o que foi alterado na chamada.

**Comment by Kkshi28** [comment]
Estou nisso agora tentando decompilar o app deles

**Comment by Kkshi28** [comment]
Mudaram :

**Comment by Kkshi28** [comment]
POST https://sinespcidadao.sinesp.gov.br/sinesp-cidadao/mobile/consultar-placa/v2
HEADERS: {"user-agent":"ksoap2-android/2.6.0+","soapaction":"","content-type":"text/xml;charset=utf-8","accept-encoding":"gzip","host":"sinespcidadao.sinesp.gov.br","connection":"Keep-Alive","content-length":"601"}
RAW BODY: <v:Envelope xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns:d="http://www.w3.org/2001/XMLSchema" xmlns:c="http://schemas.xmlsoap.org/soap/encoding/" xmlns:v="http://schemas.xmlsoap.org/soap/envelope/"><v:Header><b>Byron sp ALCATEL ONETOUCH POPC3</b><c>ANDROID</c><d>5.0.1</d><e>4.2.3</e><f>10.42.0.59</f><g>a6d271e18d333d5f160ea85683a2e029b4f02f60</g><h>0.0</h><i>0.0</i><k></k><l>2017-06-28 18:47:41</l><m>8797e74f0d6eb7b1ff3dc114d4aa12d3</m></v:Header><v:Body><n0:getStatus xmlns:n0="http://soap.ws.placa.service.sinesp.serpro.gov.br/"><a>AAA9999</a></n0:getStatus></v:Body></v:Envelope>

**Comment by Kkshi28** [comment]
Opa apagou as tag no comentário

**Comment by Kkshi28** [comment]
Ahora esta dando error en el parseXML

**Comment by Kkshi28** [comment]
Erro meu o erro qu esta dando agora é {"codigoRetorno":"6","mensagemRetorno":"Chamada para o serviço é inválida."} a unica mudança foi a url do post https://sinespcidadao.sinesp.gov.br/sinesp-cidadao/mobile/consultar-placa/v2

**Comment by bbarreto** [comment]
@Kkshi28 provavelmente o que deve ter mudado na chamada foi a variável secret que gera o token da placa, conforme o index.js do módulo:

``` php
/** Chave secreta para criptografia */
var secret = 'TRwf1iBwvCoSboSscGne';

/** Criptografa a placa usando a chave do aplicativo */
var token = crypto.createHmac('sha1', placa+secret).update(placa).digest('hex');

/** Gerar a data da requisição */
var data = new Date().toISOString().replace("T", " ").substr(0, 19);
```

**Comment by Kkshi28** [comment]
mudou a forma em que geram o token sim, estou nisso

**Comment by bbarreto** [comment]
O problema já foi resolvido no repositório do módulo: https://github.com/bbarreto/sinesp-nodejs

**Comment by Kkshi28** [comment]
testei esse modulo e da erro no certificado

**Comment by Kkshi28** [comment]
{ error:
   { Error: unable to verify the first certificate
       at Error (native)
       at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
       at emitNone (events.js:86:13)
       at TLSSocket.emit (events.js:185:7)
       at TLSSocket._finishInit (_tls_wrap.js:584:8)
       at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'UNABLE_TO_VER
IFY_LEAF_SIGNATURE' } }

**Comment by Kkshi28** [comment]
Já funcionou obrigado !!!
