### ISSUE TITLE
Servidor não retorna consulta por motivos de versão desatualizada

### ISSUE THREAD

**Issue by mateusmnc** [bbarreto/sinesp-api#5]
Boa tarde Bruno,

Estou usando a api,  e tenho feito a chamada como no exemplo, há alguns meses eu testei estava funcionado, mas agora o retorno é sempre o seguinte: 

codigoRetorno":"7","mensagemRetorno":"Versão desatualizada. Favor atualizar aplicativo.

Tem alguma solução ou sugestão em vista?

Vi que o mesmo problema já aconteceu no passado, se houver alguma maneira de ajudar me avise.

Abraço,
Mateus Manica

**Comment by mateusmnc** [comment]
Opa, 
Vi que você tem outro repositório com ele (o código) encapsulado em um módulo e com acesso via NPM, estou usando ele sem problemas. O issue ainda existe nesse repositório, no entanto não sei se tem relevância frente ao pacote NPM. 
Você que sabe daí.

**Comment by bbarreto** [comment]
O repositório oficial atualizado sempre será o do módulo NPM. github.com/bbarreto/sinesp-nodejs
