### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by marcelinhovt** [bbarreto/sinesp-api#7]
Boa noite.
Essa api nao é oficial, correto?
Nao há nenhuma api ja hospedada pra usar/testar?

Obrigado.

**Comment by bbarreto** [comment]
@marcelinhovt a API é oficial, mas a implementação não. Para testar, você pode utilizar o módulo npm https://www.npmjs.com/package/sinesp-nodejs. Na página há informações detalhadas de como baixar e testar localmente.
